// <auto-generated />
using System;
using Example.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Example.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221227072657_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Example.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = "ca8367df-ec2c-418f-b441-a3efc3131edf",
                            Country = "Data",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(2476),
                            Email = "Malcolm Turner@gmail.com",
                            FullName = "Freida Wisozk",
                            IsDeleted = false,
                            NumberPhone = "(776) 806-4242",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(2493)
                        },
                        new
                        {
                            Id = "ad6d97bd-3182-4658-b56c-fcc9161f3bfd",
                            Country = "Operations",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3442),
                            Email = "Nathanial D'Amore@gmail.com",
                            FullName = "Rogers Kiehn",
                            IsDeleted = false,
                            NumberPhone = "(534) 333-3797 x822",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3447)
                        },
                        new
                        {
                            Id = "c5f1b62a-56e6-4bd8-b4f3-5fb6245de8ad",
                            Country = "Accounts",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3688),
                            Email = "Brittany Stroman@gmail.com",
                            FullName = "Eleanora Gerlach",
                            IsDeleted = false,
                            NumberPhone = "912-697-8698",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3691)
                        },
                        new
                        {
                            Id = "c5725e41-2731-4f41-aa43-31f3f3d10607",
                            Country = "Brand",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3789),
                            Email = "Shaina Hane@gmail.com",
                            FullName = "Immanuel Kris",
                            IsDeleted = false,
                            NumberPhone = "1-232-783-3418",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3790)
                        },
                        new
                        {
                            Id = "217b0aa9-74af-4597-b7a9-c12d51f5837a",
                            Country = "Integration",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3881),
                            Email = "Kasey Jerde@gmail.com",
                            FullName = "Haylie Hand",
                            IsDeleted = false,
                            NumberPhone = "(550) 592-5865 x09486",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3883)
                        },
                        new
                        {
                            Id = "f6a16501-e56c-41a0-884c-d03a27adc4c6",
                            Country = "Security",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3982),
                            Email = "Ebba Ward@gmail.com",
                            FullName = "Elmer Schneider",
                            IsDeleted = false,
                            NumberPhone = "(861) 423-8554 x3634",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(3983)
                        },
                        new
                        {
                            Id = "faa87278-04a7-4623-ac92-7d7530910cd8",
                            Country = "Infrastructure",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4082),
                            Email = "Jaylon Ziemann@gmail.com",
                            FullName = "Jermey Zemlak",
                            IsDeleted = false,
                            NumberPhone = "1-663-573-4426",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4083)
                        },
                        new
                        {
                            Id = "8d47d59f-3bf0-400c-b4de-12938fb4e494",
                            Country = "Response",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4241),
                            Email = "Monica Dickinson@gmail.com",
                            FullName = "Terence Fadel",
                            IsDeleted = false,
                            NumberPhone = "424-255-7510",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4244)
                        },
                        new
                        {
                            Id = "8936d358-b6bb-408e-a497-2e7cd7e4e548",
                            Country = "Security",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4343),
                            Email = "Brennon Miller@gmail.com",
                            FullName = "Missouri Leffler",
                            IsDeleted = false,
                            NumberPhone = "(451) 385-0926 x60498",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4344)
                        },
                        new
                        {
                            Id = "411016bd-458c-457a-ac95-2b7ea9d3e1d7",
                            Country = "Identity",
                            CreatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4444),
                            Email = "Germaine Ruecker@gmail.com",
                            FullName = "Damion Kub",
                            IsDeleted = false,
                            NumberPhone = "776.830.5878 x078",
                            UpdatedAt = new DateTime(2022, 12, 27, 14, 26, 57, 469, DateTimeKind.Local).AddTicks(4445)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
