// <auto-generated />
using System;
using Example.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Example.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Example.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = "386cae1a-9c46-4b56-8e44-8daea8657e70",
                            Country = "Accountability",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(7865),
                            Email = "Iliana Ledner@gmail.com",
                            FullName = "Zachary Weber",
                            IsDeleted = false,
                            NumberPhone = "1-936-404-4299",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(7882)
                        },
                        new
                        {
                            Id = "b238ea11-5ada-4c69-b115-f53cc63f8cdb",
                            Country = "Security",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(8977),
                            Email = "Waldo Ward@gmail.com",
                            FullName = "Sally Steuber",
                            IsDeleted = false,
                            NumberPhone = "456.894.0401",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(8981)
                        },
                        new
                        {
                            Id = "f44a2150-5fe9-46be-b71e-b45160e0337e",
                            Country = "Communications",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9087),
                            Email = "Kirk Corwin@gmail.com",
                            FullName = "Cristal Jast",
                            IsDeleted = false,
                            NumberPhone = "331.422.2397 x723",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9089)
                        },
                        new
                        {
                            Id = "a9bcacc7-cbcc-4b45-83d6-740b6ef743c6",
                            Country = "Operations",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9183),
                            Email = "Trudie Windler@gmail.com",
                            FullName = "Julio Bergnaum",
                            IsDeleted = false,
                            NumberPhone = "830.780.7969 x394",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9184)
                        },
                        new
                        {
                            Id = "f3832fff-261c-4923-879d-96c60cf96248",
                            Country = "Implementation",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9348),
                            Email = "Carrie Olson@gmail.com",
                            FullName = "Cindy Schmeler",
                            IsDeleted = false,
                            NumberPhone = "762-496-1795 x1333",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9350)
                        },
                        new
                        {
                            Id = "3778be59-0fb3-4378-ba64-991c4707f758",
                            Country = "Interactions",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9435),
                            Email = "Lonny Krajcik@gmail.com",
                            FullName = "Wilfredo Mayert",
                            IsDeleted = false,
                            NumberPhone = "(826) 330-6805 x44041",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9436)
                        },
                        new
                        {
                            Id = "c1941d5b-00ad-4950-ba65-e9638d2788b3",
                            Country = "Assurance",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9521),
                            Email = "Justina Beatty@gmail.com",
                            FullName = "Claud Thompson",
                            IsDeleted = false,
                            NumberPhone = "(795) 999-9018",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9523)
                        },
                        new
                        {
                            Id = "8a9929dc-ab7f-4cd1-8363-c70063d88d7e",
                            Country = "Tactics",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9616),
                            Email = "Allan Hyatt@gmail.com",
                            FullName = "Daniella Thiel",
                            IsDeleted = false,
                            NumberPhone = "(825) 903-8565",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9617)
                        },
                        new
                        {
                            Id = "f0156a90-f559-4c4a-b45a-d7c45e4b1ab6",
                            Country = "Web",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9691),
                            Email = "Felipe Abbott@gmail.com",
                            FullName = "Helene Marvin",
                            IsDeleted = false,
                            NumberPhone = "881.955.9418 x924",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9692)
                        },
                        new
                        {
                            Id = "4e068800-a3d6-40d7-b4ac-eab3ce4cea83",
                            Country = "Identity",
                            CreatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9838),
                            Email = "Katlyn Roberts@gmail.com",
                            FullName = "Dorcas Wuckert",
                            IsDeleted = false,
                            NumberPhone = "(897) 973-8084 x319",
                            UpdatedAt = new DateTime(2022, 12, 27, 16, 22, 4, 605, DateTimeKind.Local).AddTicks(9840)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
